Translation into French plan policies overview
w3c/wai-plan-policies-overview pull request #7
Opened 2020-10-19 20:00 UTC by Soahmed2031

2021-03-23 00:33 UTC, remibetin requested changes
@Soahmed2031 Here is my review for this translation : thank you again for the important work you've done !

To save your time, as for previous translations, I will probably submit a PR to yours.

2021-03-23 00:33 UTC, remibetin commented on index.fr.md
> +**{% include image.html src="video-thumb-involving-users.png" alt="" class="video tiny" %} Vidéo : Vue d'ensemble : L'inclusion des utilisateurs dans l'accessibilité Web**
See all my remarks about this video section here : https://github.com/w3c/wai-InvolveUsersEval/pull/9

2021-03-23 00:33 UTC, remibetin commented on index.fr.md
> +## Ressources : lois et politiques {#policy}
Alone, the word "politiques" in french is not very easy to grasp in this context, don't you think ?
My suggestion "Lois et politiques d'accessibilité"

2021-03-23 00:33 UTC, remibetin commented on index.fr.md
> +Les ressources ci-dessous vous aident à trouver les lois et les politiques existantes, et à développer une politique pour votre organisation.
Same remark as above about "politiques"
My suggestion :
"Les ressources ci-dessous vous aident à trouver les lois et les politiques d'accessibilité existantes, et à développer une politique d'accessibilité pour votre organisation."

2021-03-23 00:33 UTC, remibetin commented on index.fr.md
> +[[Lois et politiques de l'accessibilité Web]](/policies/)
"Lois et politiques d'accessibilité web" maybe ?

2021-03-23 00:33 UTC, remibetin commented on index.fr.md
> +: décrit les considérations à prendre en compte lors de l'élaboration de politiques simples ou globales pour créer, gérer, et fournir un site Web.
- "delivering accessible websites" : at the end of the development process, we often use the word "livrer" more than "fournir" un site Web.
- My suggestion : "décrit les considérations à prendre en compte lors de l'élaboration de politiques simples ou **complètes** pour créer, gérer, et **livrer un site Web accessible.**"

2021-03-23 00:33 UTC, remibetin commented on index.fr.md
> +[[Création d'une déclaration d'accessibilité]](/planning/statements/)
Suggestion : "Mettre au point une déclaration sur l'accessibilité"
Note : In the official French translation of the EU Web Accessibility Directive, "accessibility statement" is translated into "déclaration sur l'accessibilité".

2021-03-23 00:33 UTC, remibetin commented on index.fr.md
> +: vous aide à créer une déclaration d'accessibilité pour vos propres sites Web, applications mobiles, ou autres contenus numériques.
"déclaration sur l'accessibilité" (see above)

2021-03-23 00:37 UTC, remibetin requested changes

2021-03-23 00:37 UTC, remibetin commented on index.fr.md
> +Les ressources ci-dessous vous aident à trouver les lois et les politiques existantes, et à développer une politique pour votre organisation.
There is a line missing after this one. It creates a layout different from the original version.

2021-04-02 12:39 UTC, remibetin commented
Integrated into #8

2021-04-02 18:50 UTC, slhenry commented
moved to https://github.com/w3c/wai-plan-policies-overview/pull/8 Thanks!

2021-04-02 18:50 UTC, closed without merging